spring:
  application:
    name: odin
  datasource:
    url: ${ODIN_MYSQL_URL}
    username: ${ODIN_MYSQL_USER}
    password: ${ODIN_MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect

server:
  port: 9000